propel:
    database:
        connections:
            default:
                adapter: mysql
                dsn: mysql:host=localhost:3306;dbname={{ pillar.recommendations.db.name }}
                user: {{ pillar.recommendations.db.user }}
                password: {{ pillar.recommendations.db.password }}
                settings:
                    charset: utf8
